name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@master

      - name: Install
        run: |
          sudo apt-get install lcov
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo "::set-env name=CC::gcc"
            echo "::set-env name=CXX::g++"
          else
            echo "::set-env name=CC::clang"
            echo "::set-env name=CXX::clang++"
          fi

      - name: Unit test
        run: ./unit_test.sh

      - name: Benchmark
        run: ./benchmark.sh

      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
