name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest
      
  linux-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      env:
        CC: clang
        CXX: clang++
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest
