name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@master

      - name: install
        run: |
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo "::set-env name=CC::gcc"
            echo "::set-env name=CXX::g++"
          else
            echo "::set-env name=CC::clang"
            echo "::set-env name=CXX::clang++"
          fi

      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

      - name: build
        run: cmake --build build -j 2

      - name: test
        run: cd build && ctest

      - name: benchmark
        run: ./build/benchmark/lox-benchmark
