name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-lastest
    strategy:
      max-parallel: 2
      matrix:
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@master
          cc: ${{ matrix.cc }}
      - name: configure
         run: mkdir build && cd build && cmake ..
      - name: build
         run: cmake --build build -j 2
      - name: test
         run: cd build && ctest
