name: CI

on: push

strategy:
  matrix:
    compiler: [gcc, clang]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest
