name: CI

on: push

jobs:
  linux-gcc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include: 
        - os: ubuntu-latest
          COMPILER: gcc
        - os: ubuntu-latest
          COMPILER: clang
    steps:
    - uses: actions/checkout@master
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build -j 2
    - name: test
      run: cd build && ctest
